### ISSUE TITLE
Installation error in linux

### ISSUE THREAD

**Issue by wajidali** [mindsphere/node-red-contrib-mindconnect#135]
I get error while installing on linux. Below is the error message. 

-----------------------------------------------------------
2021-06-03T13:22:21.538Z Install : @mindconnect/node-red-contrib-mindconnect 3.12.0

2021-06-03T13:22:22.687Z npm install --no-audit --no-update-notifier --save --save-prefix="~" --production @mindconnect/node-red-contrib-mindconnect@3.12.0
2021-06-03T13:22:28.377Z [err] WARN
2021-06-03T13:22:28.377Z [err]  
2021-06-03T13:22:28.377Z [err] engine
2021-06-03T13:22:28.377Z [err]  chalk@4.1.1: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
2021-06-03T13:22:28.502Z [err] npm
2021-06-03T13:22:28.503Z [err]  
2021-06-03T13:22:28.503Z [err] ERR!
2021-06-03T13:22:28.503Z [err]  Linux 4.15.0-140-generic
2021-06-03T13:22:28.503Z [err] npm
2021-06-03T13:22:28.503Z [err]  
2021-06-03T13:22:28.503Z [err] ERR!
2021-06-03T13:22:28.503Z [err]  
2021-06-03T13:22:28.503Z [err] argv
2021-06-03T13:22:28.504Z [err]  "/usr/bin/node" "/usr/bin/npm" "install" "--no-audit" "--no-update-notifier" "--save" "--save-prefix=\"~\"" "--production" "@mindconnect/node-red-contrib-mindconnect@3.12.0"
2021-06-03T13:22:28.504Z [err] npm
2021-06-03T13:22:28.504Z [err]  
2021-06-03T13:22:28.504Z [err] ERR!
2021-06-03T13:22:28.504Z [err]  
2021-06-03T13:22:28.504Z [err] node
2021-06-03T13:22:28.504Z [err]  v8.10.0
2021-06-03T13:22:28.504Z [err] npm
2021-06-03T13:22:28.504Z [err]  
2021-06-03T13:22:28.505Z [err] ERR!
2021-06-03T13:22:28.505Z [err]  
2021-06-03T13:22:28.505Z [err] npm 
2021-06-03T13:22:28.505Z [err]  v3.5.2
2021-06-03T13:22:28.505Z [err] npm
2021-06-03T13:22:28.505Z [err]  
2021-06-03T13:22:28.505Z [err] ERR!
2021-06-03T13:22:28.505Z [err]  
2021-06-03T13:22:28.505Z [err] code
2021-06-03T13:22:28.506Z [err]  EMISSINGARG
2021-06-03T13:22:28.506Z [err] 
2021-06-03T13:22:28.507Z [err] npm
2021-06-03T13:22:28.507Z [err]  
2021-06-03T13:22:28.508Z [err] ERR!
2021-06-03T13:22:28.508Z [err]  
2021-06-03T13:22:28.508Z [err] typeerror
2021-06-03T13:22:28.508Z [err]  Error: Missing required argument #1
2021-06-03T13:22:28.508Z [err] npm
2021-06-03T13:22:28.508Z [err]  
2021-06-03T13:22:28.508Z [err] ERR!
2021-06-03T13:22:28.508Z [err]  
2021-06-03T13:22:28.508Z [err] typeerror
2021-06-03T13:22:28.508Z [err]      at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
2021-06-03T13:22:28.509Z [err] npm
2021-06-03T13:22:28.509Z [err]  
2021-06-03T13:22:28.509Z [err] ERR!
2021-06-03T13:22:28.509Z [err]  
2021-06-03T13:22:28.509Z [err] typeerror
2021-06-03T13:22:28.509Z [err]      at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
2021-06-03T13:22:28.509Z [err] npm
2021-06-03T13:22:28.509Z [err]  
2021-06-03T13:22:28.509Z [err] ERR!
2021-06-03T13:22:28.509Z [err]  
2021-06-03T13:22:28.510Z [err] typeerror
2021-06-03T13:22:28.510Z [err]      at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
2021-06-03T13:22:28.510Z [err] npm
2021-06-03T13:22:28.510Z [err]  
2021-06-03T13:22:28.510Z [err] ERR!
2021-06-03T13:22:28.510Z [err]  
2021-06-03T13:22:28.510Z [err] typeerror
2021-06-03T13:22:28.510Z [err]      at /usr/share/npm/lib/install/deps.js:457:7
2021-06-03T13:22:28.510Z [err] npm
2021-06-03T13:22:28.510Z [err]  
2021-06-03T13:22:28.511Z [err] ERR!
2021-06-03T13:22:28.511Z [err]  
2021-06-03T13:22:28.511Z [err] typeerror
2021-06-03T13:22:28.511Z [err]      at /usr/share/npm/node_modules/iferr/index.js:13:50
2021-06-03T13:22:28.511Z [err] npm
2021-06-03T13:22:28.511Z [err]  
2021-06-03T13:22:28.511Z [err] ERR!
2021-06-03T13:22:28.511Z [err]  
2021-06-03T13:22:28.511Z [err] typeerror
2021-06-03T13:22:28.511Z [err]      at /usr/share/npm/lib/fetch-package-metadata.js:37:12
2021-06-03T13:22:28.512Z [err] npm
2021-06-03T13:22:28.513Z [err]  
2021-06-03T13:22:28.513Z [err] ERR!
2021-06-03T13:22:28.513Z [err]  
2021-06-03T13:22:28.513Z [err] typeerror
2021-06-03T13:22:28.513Z [err]      at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
2021-06-03T13:22:28.513Z [err] npm
2021-06-03T13:22:28.513Z [err]  
2021-06-03T13:22:28.513Z [err] ERR!
2021-06-03T13:22:28.514Z [err]  
2021-06-03T13:22:28.514Z [err] typeerror
2021-06-03T13:22:28.514Z [err]      at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
2021-06-03T13:22:28.514Z [err] npm
2021-06-03T13:22:28.514Z [err]  
2021-06-03T13:22:28.514Z [err] ERR!
2021-06-03T13:22:28.514Z [err]  
2021-06-03T13:22:28.514Z [err] typeerror
2021-06-03T13:22:28.514Z [err]      at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
2021-06-03T13:22:28.514Z [err] npm
2021-06-03T13:22:28.515Z [err]  
2021-06-03T13:22:28.515Z [err] ERR!
2021-06-03T13:22:28.515Z [err]  
2021-06-03T13:22:28.515Z [err] typeerror
2021-06-03T13:22:28.515Z [err]      at /usr/share/npm/node_modules/iferr/index.js:13:50
2021-06-03T13:22:28.515Z [err] npm
2021-06-03T13:22:28.515Z [err]  
2021-06-03T13:22:28.515Z [err] ERR!
2021-06-03T13:22:28.515Z [err]  
2021-06-03T13:22:28.515Z [err] typeerror
2021-06-03T13:22:28.516Z [err]  This is an error with npm itself. Please report this error at:
2021-06-03T13:22:28.516Z [err] npm
2021-06-03T13:22:28.516Z [err]  
2021-06-03T13:22:28.516Z [err] ERR!
2021-06-03T13:22:28.516Z [err]  
2021-06-03T13:22:28.516Z [err] typeerror
2021-06-03T13:22:28.516Z [err]      <http://github.com/npm/npm/issues>
2021-06-03T13:22:28.521Z [err] WARN
2021-06-03T13:22:28.521Z [err]  
2021-06-03T13:22:28.521Z [err] engine
2021-06-03T13:22:28.521Z [err]  update-notifier@5.1.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
2021-06-03T13:22:28.525Z [err] WARN
2021-06-03T13:22:28.526Z [err]  
2021-06-03T13:22:28.526Z [err] engine
2021-06-03T13:22:28.526Z [err]  ora@5.4.0: wanted: {"node":">=10"} (current: {"node":"8.10.0","npm":"3.5.2"})
2021-06-03T13:22:29.143Z [err] 
2021-06-03T13:22:29.143Z [err] npm
2021-06-03T13:22:29.143Z [err]  
2021-06-03T13:22:29.143Z [err] ERR!
2021-06-03T13:22:29.143Z [err]  Please include the following file with any support request:
2021-06-03T13:22:29.143Z [err] npm
2021-06-03T13:22:29.144Z [err]  
2021-06-03T13:22:29.144Z [err] ERR!
2021-06-03T13:22:29.144Z [err]      /root/.node-red/npm-debug.log
2021-06-03T13:22:29.153Z rc=1

**Comment by sn0wcat** [comment]
you have to upgrade your nodejs and your node-red to the more current version, you are currently using nodejs version 8 which is 6 version behind the current one and completely deprecated since 2020. 

Download https://nodejs.org/en/download/

installing nodejs on linux via package manager
https://nodejs.org/en/download/package-manager/
